language node_js
node_js:
  - "6.1"
  - "6.0"
  - "5.0"
  - ".12"
  - ".10"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install
  - bower install
