language: node_js

notifications:
    email: false

before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install
  - bower install
